# Generated by Django 3.0.1 on 2020-01-02 03:20

from django.db import migrations, models
import django.db.models.deletion
import playground.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='created at')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('nickname', models.CharField(max_length=32, verbose_name='nickname')),
                ('document', models.CharField(max_length=14, validators=[playground.core.validators.validate_document], verbose_name='document')),
                ('phone', models.CharField(max_length=11, validators=[playground.core.validators.validate_phone], verbose_name='phone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalPerson',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Person', verbose_name='person')),
                ('state_registration', models.CharField(max_length=32, verbose_name='state registration')),
                ('municipal_registration', models.CharField(max_length=32, verbose_name='municipal registration')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.person',),
        ),
        migrations.CreateModel(
            name='NaturalPerson',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Person', verbose_name='person')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='gender')),
                ('birthday', models.DateField(verbose_name='birthday')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.person',),
        ),
    ]
